knp_paginator:
    page_range: 5                       # Number of page links to show
    default_options:
        page_name: page                 # Query parameter name for page number
        sort_field_name: sort           # Query parameter name for sorting
        sort_direction_name: direction  # Query parameter name for sort direction
        distinct: true                  # Ensure distinct results
        filter_field_name: filterField  # Query parameter name for filter field
        filter_value_name: filterValue  # Query parameter name for filter value
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'  # Pagination template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'  # Sortable link template
