symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # Durée de validité du lien (1 heure)
    lifetime: 3600
    # Délai minimum entre deux demandes (en secondes) - 120 s en dev pour pouvoir réessayer
    throttle_limit: 120
