vich_uploader:
    db_driver: orm

    mappings:
        message_images:
            uri_prefix: /uploads/messages
            upload_destination: '%kernel.project_dir%/public/uploads/messages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
